#include<stdio.h>

int main(){

    int sayici,toplam=0,sayici2;

    for(sayici2=1;sayici2<1000;sayici2++){
        sayici=sayici2;

       if(sayici%100==0){
           if(sayici-900>=0){
               toplam+=11;
               sayici-=900;
           }
           if(sayici-800>=0){
               toplam+=12;
               sayici-=800;
           }
           if(sayici-700>=0){
               toplam+=12;
               sayici-=700;
           }
           if(sayici-600>=0){
               toplam+=10;
               sayici-=600;
           }
           if(sayici-500>=0){
               toplam+=11;
               sayici-=500;
           }
           if(sayici-400>=0){
               toplam+=11;
               sayici-=400;
           }
           if(sayici-300>=0){
               toplam+=12;
               sayici-=300;
           }
           if(sayici-200>=0){
               toplam+=10;
               sayici-=200;
           }
           if(sayici-100>=0){
               toplam+=10;
               sayici-=100;
           }

        }
       else{
        if(sayici-900>=0){
            toplam+=14;
            sayici-=900;
        }
        if(sayici-800>=0){
            toplam+=15;
            sayici-=800;
        }
        if(sayici-700>=0){
            toplam+=15;
            sayici-=700;
        }
        if(sayici-600>=0){
            toplam+=13;
            sayici-=600;
        }
        if(sayici-500>=0){
            toplam+=14;
            sayici-=500;
        }
        if(sayici-400>=0){
            toplam+=14;
            sayici-=400;
        }
        if(sayici-300>=0){
            toplam+=15;
            sayici-=300;
        }
        if(sayici-200>=0){
            toplam+=13;
            sayici-=200;
        }
        if(sayici-100>=0){
            toplam+=13;
            sayici-=100;
        }
        if(sayici-90>=0){
            toplam+=6;
            sayici-=90;
        }
        if(sayici-80>=0){
            toplam+=6;
            sayici-=80;
        }
        if(sayici-70>=0){
            toplam+=7;
            sayici-=70;
        }
        if(sayici-60>=0){
            toplam+=5;
            sayici-=60;
        }
        if(sayici-50>=0){
            toplam+=5;
            sayici-=50;
        }
        if(sayici-40>=0){
            toplam+=5;
            sayici-=40;
        }
        if(sayici-30>=0){
            toplam+=6;
            sayici-=30;
        }
        if(sayici-20>=0){
            toplam+=6;
            sayici-=20;
        }
        if(sayici-19>=0){
            toplam+=8;
            sayici-=19;
        }
        if(sayici-18>=0){
            toplam+=8;
            sayici-=18;
        }
        if(sayici-17>=0){
            toplam+=9;
            sayici-=17;
        }
        if(sayici-16>=0){
            toplam+=7;
            sayici-=16;
        }
        if(sayici-15>=0){
            toplam+=7;
            sayici-=15;
        }
        if(sayici-14>=0){
            toplam+=8;
            sayici-=14;
        }
        if(sayici-13>=0){
            toplam+=8;
            sayici-=13;
        }
        if(sayici-12>=0){
            toplam+=6;
            sayici-=12;
        }
        if(sayici-11>=0){
            toplam+=6;
            sayici-=11;
        }
        if(sayici-10>=0){
            toplam+=3;
            sayici-=10;
        }
        if(sayici-9>=0){
            toplam+=4;
            sayici-=9;
        }
        if(sayici-8>=0){
            toplam+=5;
            sayici-=8;
        }
        if(sayici-7>=0){
            toplam+=5;
            sayici-=7;
        }
        if(sayici-6>=0){
            toplam+=3;
            sayici-=6;
        }
        if(sayici-5>=0){
            toplam+=4;
            sayici-=5;
        }
        if(sayici-4>=0){
            toplam+=4;
            sayici-=4;
        }
        if(sayici-3>=0){
            toplam+=5;
            sayici-=3;
        }
        if(sayici-2>=0){
            toplam+=3;
            sayici-=2;
        }
        if(sayici-1>=0){
            toplam+=3;
            sayici-=1;
        }

        }


    }

    printf("%d\n",toplam+11);



    return 0;
}
